config/routes.rb
CrowdtapTest::Application.routes.draw do

  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resource :user_session
  
  resources :todos do
    member do
      get 'move_up'
      get 'move_down'
      get 'check'
    end
  end
  
  root :to => 'todos#index'
end

app/models/todo.rb
# coding: UTF-8

class Todo < ActiveRecord::Base
  belongs_to :user
  acts_as_list :scope => :user
  validates_presence_of :title, :user_id
  
  # Sets checked to true and saves the record.
  def check!
    update_attribute :checked, true
  end
  
  # Returns the title, preceded by a check if checked? is true.
  def title_with_check
    check_string = checked? ? '✓ ' : ''
    "#{check_string}#{title}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :todos, :order => 'position'
  validates_presence_of :email
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user_session, :current_user
  
  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end
    
    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.record
    end
    
    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to account_url
        return false
      end
    end
    
    def store_location
      session[:return_to] = request.request_uri
    end
    
    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :require_user
  inherit_resources
  
  def index
    @todo = Todo.new
  end
  
  def create
    create! { {:action => 'index'} }
  end
  
  def move_up
    quick_action :move_higher
  end
  
  def move_down
    quick_action :move_lower
  end
  
  def check
    quick_action :check!
  end
  
  private
  
  def begin_of_association_chain
    current_user
  end
  
  def quick_action(method)
    resource.send method
    redirect_to :action => 'index'
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(User.find_or_create_by_email(params[:user_session][:user]), true)
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default todos_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrowdtapTest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_todo.html.haml
%tr[todo]
  %td.actions
    = link_to 'up', move_up_todo_path(todo)
    %br
    = link_to 'down', move_down_todo_path(todo)
    - if !todo.checked?
      %br
      = link_to 'check', check_todo_path(todo)
  %td= todo.title_with_check
  %td= todo.description
  %td= todo.due_date

app/views/todos/index.html.haml
%p
  == Logged in as #{current_user.email}
  |
  = link_to 'Log out', logout_path

%h1 My Todos

%table
  %tr
    %th.actions
    %th Title
    %th Description
    %th Due date
  = render :partial => 'todo', :collection => collection

= form_for @todo do |f|
  %table
    %tr
      %th= f.label :title
      %th= f.label :description
      %th= f.label :due_date
    %tr
      %td= f.text_field :title
      %td= f.text_field :description
      %td= f.text_field :due_date
  = f.submit 'Save'

app/views/user_sessions/new.html.haml
%h1 Log in
%p Please enter your e-mail address. If you don't already have an account, we'll create one.
= form_for @user_session, :url => user_session_path do |f|
  = f.fields_for :user do |u|
    = u.label :email, 'E-mail address'
    = u.email_field :email
  = f.submit "Log in"